trigger:
  - main

variables:
  - group: GitHubSecrets

pool:
  vmImage: ubuntu-latest

steps:
  - task: NodeTool@0
    inputs:
      versionSpec: 22.x
    displayName: Install Node.js

  - script: |
      echo "//npm.pkg.github.com/:_authToken=$(GITHUB_TOKEN)" > ~/.npmrc
      npm whoami --registry=https://npm.pkg.github.com
    env:
      GITHUB_TOKEN: $(GITHUB_TOKEN)
    displayName: Authenticate with GitHub Packages

  - script: |
      npm install
    displayName: Install npm dependencies

  - script: |
      npm run copy:config
    displayName: Run copy config

  # Build step removed as requested

  - script: |
      echo "//npm.pkg.github.com/:_authToken=${GITHUB_TOKEN}" > .npmrc
      echo "@pageproof:registry=https://npm.pkg.github.com" >> .npmrc
    env:
      GITHUB_TOKEN: $(GITHUB_TOKEN)
    displayName: Copy token to .npmrc

  - script: |
      zip -r app.zip . -x "*.git*" "*.DS_Store" "node_modules/*"
    displayName: Zip entire repo (excluding .git, .DS_Store, and node_modules)

  - task: PublishPipelineArtifact@1
    inputs:
      targetPath: app.zip
      artifact: app-archive
      publishLocation: pipeline
    displayName: Publish app.zip as artifact
